### ISSUE TITLE
Calling async function from template

### ISSUE THREAD

**Issue by pvilas** [jpsca/jinjax#2]
Can we call an async function form a template?

If you have an async method

```
async def hi()-> str:
     return "hi user"
```

Then this renders nothing on a component

```
The returned value is {{hi()}}
```

But if the method is not async it renders well.

**Comment by jpsca** [comment]
Short answer: you can't

AFAIK Jinja doesn't allow awaiting async methods from the templates. Maybe calling a wrapper function that await the async function?
