### ISSUE TITLE
Image in documentation is wrong

### ISSUE THREAD

**Issue by angelellij** [jpsca/jinjax#20]
The following image contains an error in documentation:

 https://jinjax.scaletti.dev/static/img/anatomy-en.png
 
 It says:

```
 {#css form.css %}
 {#js form.js %}
```

 
 That throws an error for me. It seems it should be:

```
 {#css form.css #}
 {#js form.js #}
```

**Comment by MorizMensi** [comment]
you are absolutely right. I can confirm this.

**Comment by MorizMensi** [comment]
Might I reccomend the following replacement?
![replacement](https://github.com/jpsca/jinjax/assets/97762373/37273c05-3627-467a-a4d7-6a9f6e8f3070)

**Comment by MorizMensi** [comment]
There is another thing with this:
```html
<Button />
```
does not work due to the second issue outlined in #19.

**Comment by jpsca** [comment]
Fixed the image. Thank you
https://github.com/jpsca/jinjax/commit/5882642ffaf1193b7d9cb11c3ce8ae1922b41c5e
