### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by MorizMensi** [jpsca/jinjax#21]
In addition to #20, there is another issue with the documentation. This is not in the image, but on the page [Adding CSS and JS | Documentation](https://jinjax.scaletti.dev/guide/css-and-js/). Here you can find the instructions to add multiple external files (JavaScript and CSS) to the component:

```jinja2
{#css lorem.css ipsum.css #}
{#js foo.js bar.js #}
```

These do not work. I have tried this without success. If you include them as so, the following will be rendered:

```html
<script src="/static/components/scripts/lorem.js ipsum.js" defer=""></script>
<script src="/static/components/foo.js bar.js" defer=""></script>
```

### Correction
The correct way to import multiple files is by separating them using commas:

```jinja2
{#css lorem.css, ipsum.css #}
{#js foo.js, bar.js #}
```

### What also doesn't work
The following code snippet also doesn't work, because only the first instances of js and css import statements are used:

```jinja2
{#css lorem.css #}
{#css ipsum.css #}
{#js foo.js #}
{#js bar.js #}
```

**Comment by jpsca** [comment]
Thank you for letting me know, I have fixed the docs
