### ISSUE TITLE
Performance impact

### ISSUE THREAD

**Issue by astariul** [jpsca/jinjax#23]
I love the cleanliness JinjaX, this is a great project.

However I wonder how much impact on performance it has ?

I did a very quick benchmark (you can run it from [this colab notebook](https://colab.research.google.com/drive/1xt-mYZIjIllHI7lZvxWV0ZsDLi9lZS6U?usp=sharing))

And here is the results : 

* JinaX, `catalog.render` : 423 µs ± 9.71 µs per loop
* FastAPI Jinja2Templates : 44.3 µs ± 1.03 µs per loop

It's 10 times slower ? I mean, I'm not even sure this has an impact at all since the time is quite small in the grand scheme of things, but still...

Is there anyway to speed things up ?

**Comment by MorizMensi** [comment]
I would love a way to compile the JinjaX code so the translations into macros does not have to be made every single time in production. (= Outputting a .jinja file with only the macros instead of the JinjaX components)

**Comment by jpsca** [comment]
Addressed in https://github.com/jpsca/jinjax/pull/30
