### ISSUE TITLE
Django Setup?

### ISSUE THREAD

**Issue by wrabit** [jpsca/jinjax#31]
Hi, are there any specific steps for installing to a django app?

**Comment by DaliusBeckjr** [comment]
Do you still need help with your Django setup?

**Comment by DaliusBeckjr** [comment]
I can set up a Django project and add a readme with steps

**Comment by jpsca** [comment]
@wrabit I'm... not sure. A Django extension would be ideal, but I don't have experience writing one

**Comment by Tejaso7** [comment]
Pip install Django

**Comment by wrabit** [comment]
Thanks @jpsca. I actually wrote something to statisfy my needs here.

And oh boy, a lot of spam suddenly hitting GH issues

**Comment by balogun14** [comment]
just use python3 -m pip install <package name> and add this to your setings.py file

**Comment by andreighh** [comment]
@wrabit could you, if you want and have time of course, document the process a little? I'm sure a lot of Django devs would like to try this library.

**Comment by AhnafCodes** [comment]
I tried it out, it works. I have documented the steps in this article:

https://www.linkedin.com/pulse/using-jinjax-django-ashraf-mohammad-hvxsc/

If you find other examples or articles related to this please add the links below and also add any suggestions you might have to make the steps in my article better.
