### ISSUE TITLE
raise ComponentNotFound( jinjax.exceptions.ComponentNotFound: File with pattern `Unable to find a file named Home.jinja or one following the pattern Home.*.jinja` not found

### ISSUE THREAD

**Issue by RexsyBima** [jpsca/jinjax#39]
When i try to follow the documentation exactly the same, i want to make sure that everything is working, but why i got this raise ComponentNotFound(
jinjax.exceptions.ComponentNotFound: File with pattern `Unable to find a file named Home.jinja or one following the pattern Home.*.jinja` not found?

My code, simple flask hello world app

<img width="463" alt="image" src="https://github.com/jpsca/jinjax/assets/87449831/8d619740-bba6-4604-ae3a-a13f0f9d9434">

the output is 

<img width="950" alt="image" src="https://github.com/jpsca/jinjax/assets/87449831/20e5462c-a3f8-4fb2-adb9-c80f37323d84">

Im new into the webdev with Flask.

**Comment by RexsyBima** [comment]
Im using Python 3.12.1

**Comment by RexsyBima** [comment]
apparently you need to set it up the add folder method as

catalog.add_folder('templates/components')

not

catalog.add_folder('/templates/components')

im kinda curious, why is the "/" on the start is a big deal in this case?

**Comment by thornewolf** [comment]
That will start the search from your filesystem's "root directory"

So if your project is stored in `/rexsy/home/my-project/templates/components`, the "/" at the start is telling the program to look for files in `/templates/components` and NOT `/rexsy/home/my-project/templates/components`.

By excluding the "/" at the start it saves you from needing to write the full path each time.

**Comment by RexsyBima** [comment]
> That will start the search from your filesystem's "root directory"
> 
> So if your project is stored in `/rexsy/home/my-project/templates/components`, the "/" at the start is telling the program to look for files in `/templates/components` and NOT `/rexsy/home/my-project/templates/components`.
> 
> By excluding the "/" at the start it saves you from needing to write the full path each time.

Sorry for super late reply. yeah you right, i managed to get it working after changing the jinjax template directory. been working using this instead flask render template and its been a blast!!
