### ISSUE TITLE
Template Fragments

### ISSUE THREAD

**Issue by CiberNin** [jpsca/jinjax#40]
There are of course existing template fragment extensions for Jinja2 that would work with JinjaX, but I'm wondering if it might not be nice to build in a more "JinjaXey" syntax?

https://htmx.org/essays/template-fragments/

**Comment by jpsca** [comment]
Of course! You don't need to render a whole page, for example, what the page discusses:

```go
Contact c = getContact();
ChillTemplates.render("/contacts/detail.html#archive-ui", "contact", c);
```
 would be

```python
c = get_contact()
catalog.render("ArchiveUI", contact=c)
```
