### ISSUE TITLE
Support for mounting React components

### ISSUE THREAD

**Issue by buremba** [jpsca/jinjax#53]
Thanks for creating the library! Is there any plan to integrate with React? I was thinking it would be a good alternative to MDX, where we can mount React components. MDX's control flow is based on JSX and as Jinjat already covers these use cases, Jinjax has the potential to fill the gap for engineers who know Jinja + Python building web apps.

**Comment by utenma** [comment]
not sure what `mounting React components` means in this context, but React is very different from a template language, the only thing in common with jinja/jinjax may be a superficial similarity like the HTML like component syntax

on the other hand there are already markdown/jinja solutions, for instance [mitsune](https://mistune.lepture.com/en/latest/guide.html)
