### ISSUE TITLE
attrs.render() attributes result it nested quoted string: p=""v""

### ISSUE THREAD

**Issue by utenma** [jpsca/jinjax#56]
Html attributes, collected on `attrs` like `prop-a="hello"` result in nested string quotes like `prop-a=""hello hi""` when using `attrs.render()`

Server: Django 4

Jinja call site
```jsx
<AddToCart prop-a="hello hi" prop-b="test"/>
```

generated html

```html
<div class="flex items-center cursor-pointer h-[30px]"
     <!-- see double quotes-->
     prop-a=""hello hi""
     prop-b=""test""
>
    Add to cart
</div>
```

jinjax component

```jinja
<div class="flex items-center cursor-pointer h-[30px]"
    {{ attrs.render() }}
>
    Add to cart
</div>
```

**Comment by jpsca** [comment]
This was a bug of one of the releases, but was fixed a while ago
