### ISSUE TITLE
maintenance status

### ISSUE THREAD

**Issue by mardiros** [jpsca/jinjax#58]
Hi @jpsca 

Thank you for providing this modern template engine. I appreciate using it in my current experimentation.

I've open two merge request recently. #48 amd #50 without any feedback.

I starts asking myself if you still maintain this project ?
Could you take the time to clarify the situation here.

As I see you are working on a pydantic library (fodantic) you may also be interested of my works here.
Note that I am currently using my fork due to CSRF tokens.

https://github.com/mardiros/fastlife/tree/main/tests/unittests/templating

**Comment by jpsca** [comment]
The project is not dead or abandoned.
