### ISSUE TITLE
Jinjax does not work with flask-assets by default

### ISSUE THREAD

**Issue by SuperDoxin** [jpsca/jinjax#7]
Having code like this:
```
app = Flask(__name__)

assets = Environment(app)
css = Bundle("main.css", depends=["**/*.jinja"], output="dist/main.css", filters=[tailwindcss])

assets.register("css", css)

catalog = Catalog(
    globals=app.jinja_env.globals,
    filters=app.jinja_env.filters,
    tests=app.jinja_env.tests,
    extensions=list(app.jinja_env.extensions.keys())
)
catalog.add_folder("imgboard/static/components")
```

Will lead to flask-assets complaining about its environment being set up incorrectly. Adding the following line at the end of the above snippet fixes this issue:

```
catalog.jinja_env.assets_environment = app.jinja_env.assets_environment
```

It seems to me that the copying of the jinja env that happens when initializing a Catalog results in an incomplete copy, which leads to this issue with flask-assets but can also easily result in confusing errors when using other plugins.

**Comment by jpsca** [comment]
To avoid these kind of issues, I've updated the library to accept the Flask Jinja Environment: https://jinjax.scaletti.dev/guide/#jinja

This will fix the bug if you update JinjaX to the latest relase (0.23) and change your code to:

```python
catalog = jinjax.Catalog(jinja_env=app.jinja_env)
```

**Comment by SuperDoxin** [comment]
Wow that's a quick response! I'll give that a go next time I get to work on my project.
