### ISSUE TITLE
How to disable jinjax for specific lines

### ISSUE THREAD

**Issue by ikus060** [jpsca/jinjax#74]
Hello,

I'm very new to JinjaX and I have an issue while trying to integrate it with an existing Jinja2 application.

I have this line of code in my jinja template. It assign a very specific string value to a variable and it should not get expanded by JinjaX.
```
{% set dom_without_length_change = "<'d-sm-flex align-items-center'<'mb-1 flex-grow-1'i><'mb-1'f><B>><'row'<'col-sm-12'rt>><'row'<'mt-2'p>>" %}
```

When compiling template, I get this error.
```
jinja2.exceptions.TemplateSyntaxError: Unclosed component <B>
```
Is it possible to disable JinjaX rendering for this specific line. Or maybe there is another workaround ?

Thanks

**Comment by ikus060** [comment]
Ho I think I figure it out looking at the code. I'm not sure it's this feature is document in the doc.

```
{% raw %}
{% set dom_without_length_change = "<'d-sm-flex align-items-center'<'mb-1 flex-grow-1'i><'mb-1'f><B>><'row'<'col-sm-12'rt>><'row'<'mt-2'p>>" %}
{% endraw %}
```

**Comment by jpsca** [comment]
This works:

```html+jinja
{% set dom_without_length_change = "<'d-sm-flex align-items-center'<'mb-1 flex-grow-1'i><'mb-1'f><" + "B>><'row'<'col-sm-12'rt>><'row'<'mt-2'p>>" %}
```

Sorry, it's a crappy solution, but it works until I use a real parser instead of regular expressions
