### ISSUE TITLE
How to pass arguments down to components on 0.40

### ISSUE THREAD

**Issue by jacopofar** [jpsca/jinjax#77]
Hello!
Thanks for this library, I find it very useful!

I upgraded to version 0.4 and tried to adapt my templates to the new format, but don't know how to pass parameters down to components.

previously I had this:

```
{#def title, article_html #}
<HtmlHeader title={{ title }}/>
<body data-bs-theme="dark">
<div class="container-fluid main-content">
    <div class="row">
        <h1>{{ title }}</h1>
bla bla
```

now I do this:

```
{#def title, article_html #}
<HtmlHeader :title={{ title }}/>
<body data-bs-theme="dark">
<div class="container-fluid main-content">
    <div class="row">
        <h1>{{ title }}</h1>
bla bla
```

the issue is that the `title` parameter gets rendered in the `HtmlHeader` component as `True` instead of the string. The value of `title` inside the `<h1>` tag is correctly the content of the title parameter as a string. I tried to put quotes around it but then it becomes a syntax error:

```
    <HtmlHeader :title = "{{ title }}" />
    ^^^^^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: expected token ':', got '}'
```

**Comment by jacopofar** [comment]
Nevermind, I figured it out by looking at the tests.

The syntax to pass the parameter was

```<HtmlHeader :title="title"/>```

in this case `title` is replaced by the variable _with that name_.

While if I do

```<HtmlHeader :title="'title'"/>```
the literal value "title" is used instead of the variable content.

And can interpolate string with this syntax

```<HtmlHeader :title="'the title is: ' ~ title"/>```

so I think the problem is solved.

I didn't use Jinja in like 11 years so this may look obvious, but still good to know if somebody comes looking for this issue.

**Comment by edager** [comment]
@jacopofar thanks for this one, it wasn't obvious to me how to pass on arguments and how they were distinguished from string literals

**Comment by jpsca** [comment]
You don't need to to the double quoting, you can just `<HtmlHeader title="title" />` like before.

`name="something"` is "name is the string 'something'"
 
`:name="something"` is "name is the result of evaluating 'something'", where 'something' can be a variable or an expression like `:name="1 + 2 + 3"` (name will be `5`, the number, not a string).

Another example:

If this is a `Header` component:

```html+jinja
{#def title #}
<h1>{{ title * 3 }}</h1>
```

Then, `<Header title="10" />`
will be `<h1>101010</h1>`  (title will be treated as a string and repeated three times)

But `<Header :title="10" />`
will be `<h1>30</h1>` (title will be treated as a number and multiplied by 3)

I'm sorry that it wasn't clear before, I should have worked on writing a better documentation first.

**Comment by jpsca** [comment]
See https://github.com/jpsca/jinjax/discussions/78

**Comment by oramirite** [comment]
Unless I'm missing something, it feels like there's some idiosyncrasies and lack of consistency with the syntax now. Most situations are fine, but I was doing a lot of this in regular jinja before: 
``` DeviceInfo.jinja
{# DeviceInfo.jinja #}
<div id="{{id}}-device-info">
  {{content}}
</div>
```
This is clean and easy to read, and I like it. However, if I'm using a nested component, and I want to pass a concatenated string into the final element, I have to do this:
``` DeviceInfo.jinja
{# DeviceInfo.jinja #}
<Info id={{id+"-device-info"}}>
  {{content}}
</Info>
```
...but, the original syntax is still required for situations where I'm still working with a regular HTML element.

It would be nice to get variable substitution in strings somehow. Maybe before they're passed into a nested component?
