### ISSUE TITLE
Regression: no longer able to have comments in component argument list

### ISSUE THREAD

**Issue by JakobGM** [jpsca/jinjax#79]
This is not a huge loss, but in case it is easy to revert the regression, I just wanted to let you know that v0.40 of JinjaX lost the ability to have comments between the argument list of a component. With other words, this is no longer allowed:

```
{# def
  #
  # Card style
  ring_class: str = "ring-1 ring-black",
  rounded_class: str = "rounded-2xl md:rounded-3xl",
  #
  # Image
  image: str | None = None,
  #
  # Content
  title: str = "",
  p_class: str = "px-5 md:px-6 py-5 md:py-6",
  gap_class: str = "gap-4",
  content_class: str = "",
  #
  # Decorative layer
  layer_class: str | None = None,
  layer_height: int = 4,
#}
```

We had to remove the comments in order to get it to work under v0.40:

```
{# def
  ring_class: str = "ring-1 ring-black",
  rounded_class: str = "rounded-2xl md:rounded-3xl",

  image: str | None = None,

  title: str = "",
  p_class: str = "px-5 md:px-6 py-5 md:py-6",
  gap_class: str = "gap-4",
  content_class: str = "",

  layer_class: str | None = None,
  layer_height: int = 4,
#}
```

Just to make it clear, if the new parsing implementation is faster in any way, or offers other benefits, then I'm happy as a user to live with this change :relaxed:

As always, thanks for your work, @jpsca! We are now able to run prettier on our (ever growing) JinjaX component library with the new vue-like attrs syntax, which is a huge win for developer ergonomics :nerd_face:

**Comment by jpsca** [comment]
I had no idea people did this, or that it worked at all :open_mouth: ... but I'm going to investigate what changed

**Comment by jpsca** [comment]
@JakobGM It should be no longer necessary to remove the comments: https://github.com/jpsca/jinjax/releases/tag/0.41

**Comment by JakobGM** [comment]
Thanks, @jpsca!

There seems to be a new regression introduced in `0.41`, most likely introduced by your new fix :sweat_smile: It is triggered when the first structure after the component argument list is a comment block. Here is an example:

```
{# def
  arg,
#}

{#
  Some comment.
#}
```

The `p = ast.parse(f"def component(*, {expr}): pass")` line in JinjaX tries to parse `def component(*, arg_1, {#): pass`. Let me know if you can't reproduce it (I simplified by code example somewhat).

**Comment by jpsca** [comment]
You really like to use comments! 😄
But seriously, thank you for the bug report.
I've just published a fix:
https://github.com/jpsca/jinjax/releases/tag/0.43
