### ISSUE TITLE
Make `whitenoise` an optional dependency

### ISSUE THREAD

**Issue by jodal** [jpsca/jinjax#95]
When using JinjaX without the JS/CSS parts, and thus without the middleware, one does not really need the `whitenoise` dependency.

It would be nice if the extra dependency was made optional by using "extras". Users wanting to use it would then install `jinjax[whitenoise]` or `jinjax[middleware]` depending on how the set of extra dependencies is named.

**Comment by jpsca** [comment]
Agree! Fixed in the [latest release](https://github.com/jpsca/jinjax/releases/tag/0.47)
